const commonStyles = {
    appContainer: {
        background: 'var(--background)',
        color: 'var(--foreground)',
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        overflow: 'hidden',
        paddingBottom: 'var(--footer-height, 0px)',
    },
    navbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 2rem', background: 'var(--card)', borderBottom: '1px solid var(--border)', flexShrink: 0, zIndex: 1000 },
    navLeft: { flex: 1, display: 'flex', alignItems: 'center', gap: '0.75rem' },
    navCenter: { flex: 2, display: 'flex', justifyContent: 'center' },
    navRight: { flex: 1, display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: '0.5rem' },
    navButtonGroup: { display: 'flex', gap: '0.5rem', background: 'var(--secondary)', padding: '4px', borderRadius: 'var(--radius)' },
    navTitle: { margin: 0, fontSize: '1.25rem', fontWeight: 600 },
    mainContent: {
        flexGrow: 1,
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        position: 'relative',
    },
    scrollablePage: {
        height: '100%',
        overflowY: 'auto',
        width: '100%',
    },
    loggedInAs: { color: 'var(--muted-foreground)', whiteSpace: 'nowrap' },
    loadingContainer: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', textAlign: 'center', padding: '4rem', color: 'var(--muted-foreground)' },
    header: { textAlign: 'center', marginBottom: '2.5rem', marginTop: '2rem' },
    headerH2: { margin: '0 0 0.5rem 0', color: 'var(--foreground-heavy)' },
    headerSubtitle: { margin: 0, color: 'var(--muted-foreground)' },
    navButton: { padding: '0.5rem 1rem', border: 'none', background: 'transparent', color: 'var(--muted-foreground)', borderRadius: 'var(--radius-sm)', cursor: 'pointer', transition: 'all 0.2s ease', fontWeight: 500 },
    navButtonActive: { padding: '0.5rem 1rem', border: 'none', background: 'var(--card)', color: 'var(--primary)', borderRadius: 'var(--radius-sm)', cursor: 'pointer', fontWeight: 600, boxShadow: 'var(--shadow-sm)' },
    buttonPrimary: { background: 'var(--primary)', color: 'var(--primary-foreground)', padding: '0.6rem 1.2rem', border: 'none', borderRadius: 'var(--radius)', cursor: 'pointer', fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonSuccess: { background: 'var(--success)', color: 'var(--primary-foreground)', border: 'none', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonSecondary: { background: 'var(--secondary)', color: 'var(--secondary-foreground)', border: '1px solid var(--border)', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonWarning: { background: 'var(--warning)', color: '#000', border: 'none', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonDanger: { background: 'var(--danger)', color: 'var(--primary-foreground)', border: 'none', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonDangerOutline: { background: 'transparent', color: 'var(--danger)', border: '1px solid var(--danger)', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'all 0.2s' },
    buttonGroup: { display: 'flex', gap: '0.75rem', flexWrap: 'wrap' },
    card: { background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', marginBottom: '1.5rem', overflow: 'hidden', boxShadow: 'var(--shadow-md)' },
    cardHeader: { padding: '1rem 1.25rem', background: 'var(--secondary)', borderBottom: '1px solid var(--border)', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '0.5rem' },
    cardBody: { padding: '1.5rem' },
    cardFooter: { padding: '1rem 1.25rem', background: 'var(--secondary)', borderTop: '1px solid var(--border)' },
    label: { display: 'block', marginBottom: '0.5rem', fontWeight: '500', color: 'var(--foreground-heavy)' },
    input: { width: '100%', padding: '0.75rem', fontSize: '1rem', border: '1px solid var(--border)', borderRadius: 'var(--radius)', boxSizing: 'border-box', background: 'var(--secondary)', color: 'var(--foreground)', transition: 'all 0.2s ease' },
    textarea: {
        width: '100%',
        minHeight: '200px',
        padding: '1rem',
        fontSize: '1rem',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius)',
        boxSizing: 'border-box',
        resize: 'vertical',
        background: 'var(--secondary)',
        color: 'var(--foreground)',
        transition: 'all 0.2s ease',
        lineHeight: 1.5,
    },
    fileInput: { width: '100%', padding: '0.75rem', fontSize: '1rem', boxSizing: 'border-box', marginTop: '0.5rem', border: '1px solid var(--border)', borderRadius: 'var(--radius)' },
    formGroup: { marginBottom: '1.25rem' },
    formHelperText: { fontSize: '0.8rem', color: 'var(--muted-foreground)', marginTop: '0.5rem', fontStyle: 'italic' },
    alert: { padding: '0.8rem 1rem', border: '1px solid transparent', borderRadius: 'var(--radius)' },
    alertDanger: { color: '#842029', background: '#f8d7da', borderColor: '#f5c2c7' },
    alertSuccess: { color: '#0f5132', background: '#d1e7dd', borderColor: '#badbcc' },
    p: { padding: '1rem 1.25rem', color: 'var(--muted-foreground)', textAlign: 'center' },
    spinner: { animation: 'spin 1s linear infinite' },
};

export default commonStyles;