//rag.styles.js

const styles = {
    appContainer: {
        background: 'var(--background)',
        color: 'var(--foreground)',
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh', // ✅ replaces height
        overflow: 'auto', // ✅ allows scroll if needed
        paddingBottom: 'var(--footer-height, 0px)', // ✅ dynamically adjusts for footer height
    },
    navbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 2rem', background: 'var(--card)', borderBottom: '1px solid var(--border)', flexShrink: 0, zIndex: 1000 },
    navLeft: { flex: 1, display: 'flex', alignItems: 'center', gap: '0.75rem' },
    navCenter: { flex: 2, display: 'flex', justifyContent: 'center' },
    navRight: { flex: 1, display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: '0.5rem' },
    navButtonGroup: { display: 'flex', gap: '0.5rem', background: 'var(--secondary)', padding: '4px', borderRadius: 'var(--radius)' },
    navTitle: { margin: 0, fontSize: '1.25rem', fontWeight: 600 },
    mainContent: {
        flexGrow: 1,
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
    },
    loggedInAs: { color: 'var(--muted-foreground)', whiteSpace: 'nowrap' },
    loadingContainer: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', textAlign: 'center', padding: '4rem', color: 'var(--muted-foreground)' },
    header: { textAlign: 'center', marginBottom: '2.5rem', marginTop: '2rem' },
    headerH2: { margin: '0 0 0.5rem 0', color: 'var(--foreground-heavy)' },
    headerSubtitle: { margin: 0, color: 'var(--muted-foreground)' },
    navButton: { padding: '0.5rem 1rem', border: 'none', background: 'transparent', color: 'var(--muted-foreground)', borderRadius: 'var(--radius-sm)', cursor: 'pointer', transition: 'all 0.2s ease', fontWeight: 500 },
    navButtonActive: { padding: '0.5rem 1rem', border: 'none', background: 'var(--card)', color: 'var(--primary)', borderRadius: 'var(--radius-sm)', cursor: 'pointer', fontWeight: 600, boxShadow: 'var(--shadow-sm)' },
    buttonPrimary: { background: 'var(--primary)', color: 'var(--primary-foreground)', padding: '0.6rem 1.2rem', border: 'none', borderRadius: 'var(--radius)', cursor: 'pointer', fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonSuccess: { background: 'var(--success)', color: 'var(--primary-foreground)', border: 'none', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonSecondary: { background: 'var(--secondary)', color: 'var(--secondary-foreground)', border: '1px solid var(--border)', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonWarning: { background: 'var(--warning)', color: '#000', border: 'none', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonDanger: { background: 'var(--danger)', color: 'var(--primary-foreground)', border: 'none', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'background-color 0.2s' },
    buttonDangerOutline: { background: 'transparent', color: 'var(--danger)', border: '1px solid var(--danger)', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500, transition: 'all 0.2s' },
    buttonGroup: { display: 'flex', gap: '0.75rem', flexWrap: 'wrap' },
    card: { background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', marginBottom: '1.5rem', overflow: 'hidden', boxShadow: 'var(--shadow-md)' },
    cardHeader: { padding: '1rem 1.25rem', background: 'var(--secondary)', borderBottom: '1px solid var(--border)', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '0.5rem' },
    cardBody: { padding: '1.5rem' },
    cardFooter: { padding: '1rem 1.25rem', background: 'var(--secondary)', borderTop: '1px solid var(--border)' },
    label: { display: 'block', marginBottom: '0.5rem', fontWeight: '500', color: 'var(--foreground-heavy)' },
    input: { width: '100%', padding: '0.75rem', fontSize: '1rem', border: '1px solid var(--border)', borderRadius: 'var(--radius)', boxSizing: 'border-box', background: 'var(--secondary)', color: 'var(--foreground)', transition: 'all 0.2s ease' },
    textarea: {
        width: '100%',
        minHeight: '200px', // ⬆️ makes both bigger
        padding: '1rem',
        fontSize: '1rem',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius)',
        boxSizing: 'border-box',
        resize: 'vertical',
        background: 'var(--secondary)',
        color: 'var(--foreground)',
        transition: 'all 0.2s ease',
        lineHeight: 1.5,
    },
    fileInput: { width: '100%', padding: '0.75rem', fontSize: '1rem', boxSizing: 'border-box', marginTop: '0.5rem', border: '1px solid var(--border)', borderRadius: 'var(--radius)' },
    formGroup: { marginBottom: '1.25rem' },
    formHelperText: { fontSize: '0.8rem', color: 'var(--muted-foreground)', marginTop: '0.5rem', fontStyle: 'italic' },
    dashboardNav: { display: 'flex', gap: '0.5rem', borderBottom: '1px solid var(--border)', marginBottom: '1.5rem', flexWrap: 'wrap' },
    dashboardNavButton: { padding: '0.75rem 1rem', color: 'var(--muted-foreground)', border: 'none', background: 'transparent', cursor: 'pointer', borderBottom: '3px solid transparent', display: 'flex', alignItems: 'center', gap: '0.5rem', transition: 'color 0.2s, border-color 0.2s' },
    dashboardNavButtonActive: { padding: '0.75rem 1rem', border: 'none', background: 'transparent', cursor: 'pointer', borderBottom: '3px solid var(--primary)', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)', fontWeight: 600 },
    categoryHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 1.25rem' },
    categoryTitle: { fontWeight: '600', display: 'flex', alignItems: 'center', gap: '0.5rem' },
    indexStatus: { color: '#fff', padding: '0.2rem 0.6rem', borderRadius: '12px', fontSize: '0.75rem', marginLeft: '1rem', textTransform: 'uppercase', fontWeight: 600 },
    fileList: { listStyle: 'none', padding: '0 1.25rem 1rem', margin: 0 },
    fileListItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between', // MODIFIED
        gap: '1rem', // MODIFIED
        padding: '0.75rem 0', // MODIFIED
        borderBottom: '1px solid var(--border)',
        color: 'var(--muted-foreground)',
        flexWrap: 'wrap' // MODIFIED
    },
    // NEW STYLES
    fileInfoMain: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        fontWeight: 500,
        color: 'var(--foreground-heavy)',
        flexShrink: 1,
        minWidth: '200px',
        wordBreak: 'break-all' // Handle long filenames
    },
    fileInfoMeta: {
        display: 'flex',
        alignItems: 'center',
        gap: '1.5rem', // Space between size and date
        fontSize: '0.85rem',
        color: 'var(--muted-foreground)',
        flexShrink: 0,
        textAlign: 'right',
        whiteSpace: 'nowrap'
    },
    // END NEW STYLES
    chatContainer: { display: 'flex', flexDirection: 'column', height: '100%', background: 'var(--chat-bg)', overflow: 'hidden' },
    chatHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 1.5rem', borderBottom: '1px solid var(--border)', flexShrink: 0, gap: '1rem' },
    chatHeaderInfo: { display: 'flex', alignItems: 'center', gap: '0.75rem', flexGrow: 1, justifyContent: 'center' },
    chatHeaderInfoChip: { display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--muted-foreground)', background: 'var(--secondary)', padding: '6px 12px', borderRadius: '99px', fontSize: '0.9rem', fontWeight: 500 },
    personaDropdownWrapper: { position: 'relative', display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'var(--secondary)', padding: '6px 12px', borderRadius: '99px', color: 'var(--muted-foreground)', fontWeight: 500 },
    personaDropdown: { background: 'transparent', border: 'none', outline: 'none', appearance: 'none', cursor: 'pointer', color: 'var(--foreground-heavy)', fontSize: '0.9rem', fontWeight: 500, paddingRight: '1rem' },
    personaDropdownIcon: { position: 'absolute', right: '8px', pointerEvents: 'none' },
    backButton: { padding: '0.5rem', background: 'transparent', border: 'none', cursor: 'pointer', borderRadius: '50%', transition: 'background-color 0.2s', fontWeight: 500, color: 'var(--muted-foreground)' },
    iconButton: { background: 'transparent', border: 'none', cursor: 'pointer', color: 'var(--muted-foreground)', borderRadius: '50%', padding: '0.5rem', transition: 'background-color 0.2s' },
    chatHistory: { flexGrow: 1, overflowY: 'auto', padding: '1.5rem' },
    chatHistoryContent: { maxWidth: '800px', width: '100%', margin: '0 auto' },
    emptyChat: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--muted-foreground)', textAlign: 'center', gap: '1rem', padding: '1rem' },
    userMessage: { display: 'flex', justifyContent: 'flex-end', marginBottom: '1rem', gap: '0.75rem', marginLeft: 'auto', maxWidth: '100%', alignItems: 'flex-start' },
    aiMessage: { display: 'flex', justifyContent: 'flex-start', marginBottom: '1rem', gap: '0.75rem', marginRight: 'auto', maxWidth: '100%', alignItems: 'flex-start' },
    messageAvatar: { flexShrink: 0, borderRadius: '50%', width: '36px', height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--secondary)', color: 'var(--muted-foreground)', border: '1px solid var(--border)', marginTop: '4px' },
    aiMessageContent: { padding: '0.75rem 1.25rem', borderRadius: '20px', background: 'var(--ai-bubble-bg)', wordBreak: 'break-word', lineHeight: 1.6, color: 'var(--foreground)' },
    userMessageContent: { padding: '0.75rem 1.25rem', borderRadius: '20px', background: 'var(--primary-gradient)', color: 'var(--primary-foreground)', wordBreak: 'break-word', lineHeight: 1.6 },
    sourcesContainer: { fontSize: '0.8rem', color: 'var(--muted-foreground)', marginTop: '0.75rem', borderTop: '1px solid var(--border)', paddingTop: '0.75rem' },
    starRatingContainer: { marginTop: '0.75rem', borderTop: '1px solid var(--border)', paddingTop: '0.75rem', display: 'flex', gap: '4px' },
    starButton: { background: 'none', border: 'none', cursor: 'pointer', padding: '2px' },
    chatInputContainer: { padding: '1rem', background: 'var(--chat-bg)', flexShrink: 0 },
    chatInputArea: { width: '100%', maxWidth: '800px', margin: '0 auto' },
    inputWrapper: { position: 'relative', display: 'flex', alignItems: 'center', background: 'var(--card)', borderRadius: '1.75rem', padding: '0.5rem', boxShadow: 'var(--shadow-lg)', border: '1px solid var(--border)' },
    chatInput: { flexGrow: 1, padding: '0.75rem 1rem', border: 'none', resize: 'none', outline: 'none', background: 'transparent', color: 'var(--foreground)', fontSize: '1rem', lineHeight: '1.5', maxHeight: '150px' },
    sendButton: { width: '44px', height: '44px', borderRadius: '50%', border: 'none', background: 'var(--primary-light)', color: 'var(--primary)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, transition: 'all 0.2s' },
    sendButtonDisabled: { background: 'var(--muted-foreground)', cursor: 'not-allowed' },
    personaItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)' },
    personaName: { margin: 0, fontWeight: 600 },
    personaPrompt: { margin: '0.25rem 0 0', color: 'var(--muted-foreground)', fontSize: '0.9rem' },
    apiKeyTypeChip: { background: 'var(--border)', color: 'var(--muted-foreground)', padding: '0.2rem 0.6rem', borderRadius: '12px', fontSize: '0.75rem', marginLeft: '0.5rem', display: 'inline-block', fontWeight: 500 },
    statusIndicator: { width: '10px', height: '10px', borderRadius: '50%', flexShrink: 0 },
    personaStages: { marginTop: '0.5rem', fontSize: '0.8rem', color: '#666', fontStyle: 'italic' },
    personaActions: { display: 'flex', gap: '0.5rem' },
    complianceContentPreview: { margin: '0.5rem 0 0', color: 'var(--muted-foreground)', fontSize: '0.85rem', whiteSpace: 'pre-wrap', background: 'var(--secondary)', padding: '0.5rem', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border)', maxHeight: '100px', overflow: 'hidden' },
    shareGroup: { marginBottom: '1.5rem', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' },
    shareGroupTitle: { margin: 0, padding: '1rem 1.25rem', background: 'var(--secondary)', borderBottom: '1px solid var(--border)', fontWeight: 600 },
    voiceModeContainer: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'linear-gradient(180deg, #1e1e1e 0%, #121212 100%)', zIndex: 2000, display: 'flex', alignItems: 'center', justifyContent: 'center' },
    voiceFullScreen: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', height: '100%', width: '100%', color: 'white', padding: '2rem', boxSizing: 'border-box' },
    liveTranscriptContainer: { width: '100%', flex: 1, overflowY: 'auto', padding: '1rem 0', marginBottom: 'auto' },
    voiceStatusText: { fontSize: '1.2rem', margin: '1.5rem 0', color: '#aaa', height: '40px' },
    voiceMicIcon: { background: 'rgba(255,255,255,0.1)', color: '#999', border: '2px solid rgba(255,255,255,0.2)', width: '90px', height: '90px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s', userSelect: 'none' },
    voiceMicIconListening: { background: 'var(--primary)', color: 'white', border: '2px solid var(--primary)', animation: 'pulse 2s infinite' },
    voiceStopButton: { background: 'var(--danger)', color: 'white', border: 'none', width: '70px', height: '70px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'opacity 0.3s' },
    voiceExitButton: { position: 'absolute', top: '1.5rem', right: '1.5rem', background: 'rgba(50,50,50,0.7)', color: 'white', border: 'none', width: '44px', height: '44px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(16, 24, 40, 0.6)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 3000, padding: '1rem' },
    modalContent: {
        background: 'var(--card)',
        color: 'var(--foreground)',
        padding: '0',
        borderRadius: 'var(--radius-lg)',
        position: 'relative',
        width: '95%',
        maxWidth: '780px', // ⬆️ wider than 600px
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: 'var(--shadow-lg)',
        overflow: 'hidden'
    },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', flexShrink: 0 },
    modalBody: { padding: '1.5rem', overflowY: 'auto', flexGrow: 1 },
    modalCloseButton: { background: 'transparent', border: 'none', color: 'var(--muted-foreground)', cursor: 'pointer', borderRadius: '50%', padding: '0.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    modalTitle: { margin: '0', fontSize: '1.125rem', fontWeight: 600, color: 'var(--foreground-heavy)' },
    modalFooter: { display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', padding: '1rem 1.5rem', borderTop: '1px solid var(--border)', background: 'var(--secondary)', flexShrink: 0 },
    searchWrapper: { position: 'relative', margin: '1rem 0' },
    searchIcon: { position: 'absolute', top: '50%', left: '1rem', transform: 'translateY(-50%)', color: 'var(--muted-foreground)' },
    searchInput: { width: '100%', padding: '0.75rem 1rem 0.75rem 2.5rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)', background: 'var(--secondary)', color: 'var(--foreground)', fontSize: '1rem', boxSizing: 'border-box' },
    voiceListContainer: { flex: 1, overflowY: 'auto', paddingRight: '10px' },
    langHeader: { background: 'var(--secondary)', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', marginTop: '1rem', marginBottom: '0.5rem', position: 'sticky', top: 0, fontWeight: 600 },
    voiceItem: { display: 'flex', alignItems: 'center', padding: '0.75rem 1rem', borderBottom: '1px solid var(--border)', gap: '0.5rem' },
    playDemoButtonSmall: { background: 'transparent', border: 'none', color: 'var(--muted-foreground)', cursor: 'pointer', padding: '0.5rem' },
    selectButton: { background: 'var(--primary)', color: 'var(--primary-foreground)', border: 'none', padding: '0.4rem 0.8rem', borderRadius: 'var(--radius)', cursor: 'pointer', marginLeft: 'auto' },
    selectButtonActive: { background: 'var(--success)', color: 'var(--primary-foreground)', border: 'none', padding: '0.4rem 0.8rem', borderRadius: 'var(--radius)', cursor: 'pointer', marginLeft: 'auto' },
    permissionsContainer: { borderTop: '1px solid var(--border)', marginTop: '1rem' },
    permissionsHeader: { padding: '1rem 1.25rem', background: 'var(--secondary)', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '0.5rem' },
    permissionsBody: { padding: '0.5rem 1.5rem 1.5rem 1.5rem' },
    permissionUserRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.5rem 0' },
    rulebookContainer: { borderTop: '1px solid var(--border)' },
    rulebookToggleButton: { width: '100%', background: 'var(--secondary)', color: 'var(--foreground)', border: 'none', padding: '1rem 1.25rem', textAlign: 'left', cursor: 'pointer', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '0.5rem' },
    rulebookEditor: { padding: '1.5rem', background: 'var(--secondary)' },
    rulebookHelpText: { fontSize: '0.9rem', color: 'var(--muted-foreground)', margin: '0 0 1rem 0', lineHeight: 1.5, background: 'var(--card)', padding: '0.75rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)' },
    rulebookTextarea: { width: '100%', boxSizing: 'border-box', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: '0.75rem', fontFamily: 'monospace', fontSize: '0.9rem', background: 'var(--card)', color: 'var(--foreground)' },
    rulebookFooter: { display: 'flex', alignItems: 'center', gap: '1rem', marginTop: '1rem' },
    personaSelectorContainer: { borderTop: '1px solid var(--border)' },
    personaSelectorBody: { padding: '1.5rem', display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' },
    complianceContent: { margin: '0.25rem 0 0', color: 'var(--muted-foreground)', fontSize: '0.9rem', whiteSpace: 'pre-wrap', background: 'var(--secondary)', padding: '0.5rem', borderRadius: 'var(--radius-sm)' },
    alert: { padding: '0.8rem 1rem', border: '1px solid transparent', borderRadius: 'var(--radius)' },
    alertDanger: { color: '#842029', background: '#f8d7da', borderColor: '#f5c2c7' },
    alertSuccess: { color: '#0f5132', background: '#d1e7dd', borderColor: '#badbcc' },
    p: { padding: '1rem 1.25rem', color: 'var(--muted-foreground)', textAlign: 'center' },
    spinner: { animation: 'spin 1s linear infinite' },
    complianceTestControls: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', background: 'var(--card)', padding: '1rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)', flexWrap: 'wrap' },
    testResultsContainer: { marginTop: '1.5rem', },
    testResultsHeader: { marginBottom: '1rem', color: 'var(--foreground-heavy)' },
    testResultItem: { background: 'var(--card)', padding: '1rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)', marginBottom: '1rem' },
    testResultQuestion: { margin: 0, fontWeight: '500' },
    testResultAnswer: { marginTop: '0.75rem', paddingTop: '0.75rem', borderTop: '1px solid var(--border)', color: 'var(--muted-foreground)' },
    promptContainer: {
        display: 'flex',
        gap: '1.5rem',
        flexWrap: 'wrap', // ⬅️ ensures it wraps nicely on smaller screens
        alignItems: 'flex-start',
        marginBottom: '1.25rem',
    },
    promptColumn: {
        flex: 1,
        minWidth: '320px', // ⬅️ ensures proper size balance
        display: 'flex',
        flexDirection: 'column',
    },
    voiceSettingsSection: { marginBottom: '1.5rem' },
    voiceSettingsHeader: { fontWeight: 600, color: 'var(--foreground-heavy)', marginBottom: '0.75rem', paddingBottom: '0.5rem', borderBottom: `1px solid var(--border)` },
    providerToggleContainer: { display: 'flex', gap: '0.5rem', flexWrap: 'wrap' },
    providerButton: {
        flex: 1,
        background: 'var(--secondary)',
        border: '1px solid var(--border)',
        padding: '0.75rem 1rem',
        borderRadius: 'var(--radius)',
        cursor: 'pointer',
        fontWeight: 500,
        transition: 'all 0.2s',
        color: 'var(--foreground)'
    },
    providerButtonActive: {
        flex: 1,
        background: 'var(--primary-light)',
        border: '1px solid var(--primary)',
        padding: '0.75rem 1rem',
        borderRadius: 'var(--radius)',
        cursor: 'pointer',
        fontWeight: 600,
        transition: 'all 0.2s',
        color: 'var(--primary)',
        boxShadow: '0 0 0 3px var(--primary-light)',
    },
    // Autocomplete dropdown styles
    autocompleteDropdown: {
        position: 'absolute',
        bottom: '100%',
        left: 0,
        right: 0,
        marginBottom: '0.5rem',
        background: 'var(--card)',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: 'var(--shadow-lg)',
        maxHeight: '300px',
        overflowY: 'auto',
        zIndex: 1000,
    },
    autocompleteHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        padding: '0.75rem 1rem',
        background: 'var(--secondary)',
        borderBottom: '1px solid var(--border)',
        fontWeight: 600,
        fontSize: '0.85rem',
        color: 'var(--muted-foreground)',
        position: 'sticky',
        top: 0,
        zIndex: 1,
    },
    autocompleteItem: {
        padding: '0.75rem 1rem',
        cursor: 'pointer',
        transition: 'background-color 0.15s',
        borderBottom: '1px solid var(--border)',
        fontFamily: 'monospace',
        fontSize: '0.9rem',
    },
    autocompleteItemSelected: {
        background: 'var(--primary-light)',
        color: 'var(--primary)',
        fontWeight: 600,
    }
};

export default styles;