import commonStyles from '../rag.styles';

const queryStyles = {
    ...commonStyles,
    chatContainer: { display: 'flex', flexDirection: 'column', height: '100%', background: 'var(--chat-bg)', overflow: 'hidden' },
    chatHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 1.5rem', borderBottom: '1px solid var(--border)', flexShrink: 0, gap: '1rem' },
    chatHeaderInfo: { display: 'flex', alignItems: 'center', gap: '0.75rem', flexGrow: 1, justifyContent: 'center' },
    chatHeaderInfoChip: { display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--muted-foreground)', background: 'var(--secondary)', padding: '6px 12px', borderRadius: '99px', fontSize: '0.9rem', fontWeight: 500 },
    personaDropdownWrapper: { position: 'relative', display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'var(--secondary)', padding: '6px 12px', borderRadius: '99px', color: 'var(--muted-foreground)', fontWeight: 500 },
    personaDropdown: { background: 'transparent', border: 'none', outline: 'none', appearance: 'none', cursor: 'pointer', color: 'var(--foreground-heavy)', fontSize: '0.9rem', fontWeight: 500, paddingRight: '1rem' },
    personaDropdownIcon: { position: 'absolute', right: '8px', pointerEvents: 'none' },
    backButton: { padding: '0.5rem', background: 'transparent', border: 'none', cursor: 'pointer', borderRadius: '50%', transition: 'background-color 0.2s', fontWeight: 500, color: 'var(--muted-foreground)' },
    iconButton: { background: 'transparent', border: 'none', cursor: 'pointer', color: 'var(--muted-foreground)', borderRadius: '50%', padding: '0.5rem', transition: 'background-color 0.2s' },
    chatHistory: { flexGrow: 1, overflowY: 'auto', padding: '1.5rem' },
    chatHistoryContent: { maxWidth: '800px', width: '100%', margin: '0 auto' },
    emptyChat: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--muted-foreground)', textAlign: 'center', gap: '1rem', padding: '1rem' },
    userMessage: { display: 'flex', justifyContent: 'flex-end', marginBottom: '1rem', gap: '0.75rem', marginLeft: 'auto', maxWidth: '100%', alignItems: 'flex-start' },
    aiMessage: { display: 'flex', justifyContent: 'flex-start', marginBottom: '1rem', gap: '0.75rem', marginRight: 'auto', maxWidth: '100%', alignItems: 'flex-start' },
    messageAvatar: { flexShrink: 0, borderRadius: '50%', width: '36px', height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--secondary)', color: 'var(--muted-foreground)', border: '1px solid var(--border)', marginTop: '4px' },
    aiMessageContent: { padding: '0.75rem 1.25rem', borderRadius: '20px', background: 'var(--ai-bubble-bg)', wordBreak: 'break-word', lineHeight: 1.6, color: 'var(--foreground)' },
    userMessageContent: { padding: '0.75rem 1.25rem', borderRadius: '20px', background: 'var(--primary-gradient)', color: 'var(--primary-foreground)', wordBreak: 'break-word', lineHeight: 1.6 },
    sourcesContainer: { fontSize: '0.8rem', color: 'var(--muted-foreground)', marginTop: '0.75rem', borderTop: '1px solid var(--border)', paddingTop: '0.75rem' },
    starRatingContainer: { marginTop: '0.75rem', borderTop: '1px solid var(--border)', paddingTop: '0.75rem', display: 'flex', gap: '4px' },
    starButton: { background: 'none', border: 'none', cursor: 'pointer', padding: '2px' },
    chatInputContainer: { padding: '1rem', background: 'var(--chat-bg)', flexShrink: 0 },
    chatInputArea: { width: '100%', maxWidth: '800px', margin: '0 auto' },
    inputWrapper: { position: 'relative', display: 'flex', alignItems: 'center', background: 'var(--card)', borderRadius: '1.75rem', padding: '0.5rem', boxShadow: 'var(--shadow-lg)', border: '1px solid var(--border)' },
    chatInput: { flexGrow: 1, padding: '0.75rem 1rem', border: 'none', resize: 'none', outline: 'none', background: 'transparent', color: 'var(--foreground)', fontSize: '1rem', lineHeight: '1.5', maxHeight: '150px' },
    sendButton: { width: '44px', height: '44px', borderRadius: '50%', border: 'none', background: 'var(--primary-light)', color: 'var(--primary)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, transition: 'all 0.2s' },
    sendButtonDisabled: { background: 'var(--muted-foreground)', cursor: 'not-allowed' },
    personaItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)' },
    personaName: { margin: 0, fontWeight: 600 },
    personaPrompt: { margin: '0.25rem 0 0', color: 'var(--muted-foreground)', fontSize: '0.9rem' },
    personaActions: { display: 'flex', gap: '0.5rem' },
    voiceModeContainer: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'linear-gradient(180deg, #1e1e1e 0%, #121212 100%)', zIndex: 2000, display: 'flex', alignItems: 'center', justifyContent: 'center' },
    voiceFullScreen: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', height: '100%', width: '100%', color: 'white', padding: '2rem', boxSizing: 'border-box' },
    liveTranscriptContainer: { width: '100%', flex: 1, overflowY: 'auto', padding: '1rem 0', marginBottom: 'auto' },
    voiceStatusText: { fontSize: '1.2rem', margin: '1.5rem 0', color: '#aaa', height: '40px' },
    voiceMicIcon: { background: 'rgba(255,255,255,0.1)', color: '#999', border: '2px solid rgba(255,255,255,0.2)', width: '90px', height: '90px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s', userSelect: 'none' },
    voiceMicIconListening: { background: 'var(--primary)', color: 'white', border: '2px solid var(--primary)', animation: 'pulse 2s infinite' },
    voiceStopButton: { background: 'var(--danger)', color: 'white', border: 'none', width: '70px', height: '70px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'opacity 0.3s' },
    voiceExitButton: { position: 'absolute', top: '1.5rem', right: '1.5rem', background: 'rgba(50,50,50,0.7)', color: 'white', border: 'none', width: '44px', height: '44px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(16, 24, 40, 0.6)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 3000, padding: '1rem' },
    modalContent: {
        background: 'var(--card)',
        color: 'var(--foreground)',
        padding: '0',
        borderRadius: 'var(--radius-lg)',
        position: 'relative',
        width: '95%',
        maxWidth: '780px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: 'var(--shadow-lg)',
        overflow: 'hidden'
    },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', flexShrink: 0 },
    modalBody: { padding: '1.5rem', overflowY: 'auto', flexGrow: 1 },
    modalCloseButton: { background: 'transparent', border: 'none', color: 'var(--muted-foreground)', cursor: 'pointer', borderRadius: '50%', padding: '0.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    modalTitle: { margin: '0', fontSize: '1.125rem', fontWeight: 600, color: 'var(--foreground-heavy)' },
    modalFooter: { display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', padding: '1rem 1.5rem', borderTop: '1px solid var(--border)', background: 'var(--secondary)', flexShrink: 0 },
    searchWrapper: { position: 'relative', margin: '1rem 0' },
    searchIcon: { position: 'absolute', top: '50%', left: '1rem', transform: 'translateY(-50%)', color: 'var(--muted-foreground)' },
    searchInput: { width: '100%', padding: '0.75rem 1rem 0.75rem 2.5rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)', background: 'var(--secondary)', color: 'var(--foreground)', fontSize: '1rem', boxSizing: 'border-box' },
    voiceListContainer: { flex: 1, overflowY: 'auto', paddingRight: '10px' },
    langHeader: { background: 'var(--secondary)', padding: '0.5rem 1rem', borderRadius: 'var(--radius)', marginTop: '1rem', marginBottom: '0.5rem', position: 'sticky', top: 0, fontWeight: 600 },
    voiceItem: { display: 'flex', alignItems: 'center', padding: '0.75rem 1rem', borderBottom: '1px solid var(--border)', gap: '0.5rem' },
    playDemoButtonSmall: { background: 'transparent', border: 'none', color: 'var(--muted-foreground)', cursor: 'pointer', padding: '0.5rem' },
    selectButton: { background: 'var(--primary)', color: 'var(--primary-foreground)', border: 'none', padding: '0.4rem 0.8rem', borderRadius: 'var(--radius)', cursor: 'pointer', marginLeft: 'auto' },
    selectButtonActive: { background: 'var(--success)', color: 'var(--primary-foreground)', border: 'none', padding: '0.4rem 0.8rem', borderRadius: 'var(--radius)', cursor: 'pointer', marginLeft: 'auto' },
    voiceSettingsSection: { marginBottom: '1.5rem' },
    voiceSettingsHeader: { fontWeight: 600, color: 'var(--foreground-heavy)', marginBottom: '0.75rem', paddingBottom: '0.5rem', borderBottom: `1px solid var(--border)` },
    providerToggleContainer: { display: 'flex', gap: '0.5rem', flexWrap: 'wrap' },
    providerButton: {
        flex: 1,
        background: 'var(--secondary)',
        border: '1px solid var(--border)',
        padding: '0.75rem 1rem',
        borderRadius: 'var(--radius)',
        cursor: 'pointer',
        fontWeight: 500,
        transition: 'all 0.2s',
        color: 'var(--foreground)'
    },
    providerButtonActive: {
        flex: 1,
        background: 'var(--primary-light)',
        border: '1px solid var(--primary)',
        padding: '0.75rem 1rem',
        borderRadius: 'var(--radius)',
        cursor: 'pointer',
        fontWeight: 600,
        transition: 'all 0.2s',
        color: 'var(--primary)',
        boxShadow: '0 0 0 3px var(--primary-light)',
    },
    autocompleteDropdown: {
        position: 'absolute',
        bottom: '100%',
        left: 0,
        right: 0,
        marginBottom: '0.5rem',
        background: 'var(--card)',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: 'var(--shadow-lg)',
        maxHeight: '300px',
        overflowY: 'auto',
        zIndex: 1000,
    },
    autocompleteHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        padding: '0.75rem 1rem',
        background: 'var(--secondary)',
        borderBottom: '1px solid var(--border)',
        fontWeight: 600,
        fontSize: '0.85rem',
        color: 'var(--muted-foreground)',
        position: 'sticky',
        top: 0,
        zIndex: 1,
    },
    autocompleteItem: {
        padding: '0.75rem 1rem',
        cursor: 'pointer',
        transition: 'background-color 0.15s',
        borderBottom: '1px solid var(--border)',
        fontFamily: 'monospace',
        fontSize: '0.9rem',
    },
    autocompleteItemSelected: {
        background: 'var(--primary-light)',
        color: 'var(--primary)',
        fontWeight: 600,
    }
};

export default queryStyles;
