import commonStyles from '../rag.styles';

const adminStyles = {
    ...commonStyles,
    permissionsContainer: { borderTop: '1px solid var(--border)', marginTop: '1rem' },
    permissionsHeader: { padding: '1rem 1.25rem', background: 'var(--secondary)', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '0.5rem' },
    permissionsBody: { padding: '0.5rem 1.5rem 1.5rem 1.5rem' },
    permissionUserRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.5rem 0' },
    rulebookContainer: { borderTop: '1px solid var(--border)' },
    rulebookToggleButton: { width: '100%', background: 'var(--secondary)', color: 'var(--foreground)', border: 'none', padding: '1rem 1.25rem', textAlign: 'left', cursor: 'pointer', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '0.5rem' },
    rulebookEditor: { padding: '1.5rem', background: 'var(--secondary)' },
    rulebookHelpText: { fontSize: '0.9rem', color: 'var(--muted-foreground)', margin: '0 0 1rem 0', lineHeight: 1.5, background: 'var(--card)', padding: '0.75rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)' },
    rulebookTextarea: { width: '100%', boxSizing: 'border-box', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: '0.75rem', fontFamily: 'monospace', fontSize: '0.9rem', background: 'var(--card)', color: 'var(--foreground)' },
    rulebookFooter: { display: 'flex', alignItems: 'center', gap: '1rem', marginTop: '1rem' },
    personaSelectorContainer: { borderTop: '1px solid var(--border)' },
    personaSelectorBody: { padding: '1.5rem', display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' },
    complianceContent: { margin: '0.25rem 0 0', color: 'var(--muted-foreground)', fontSize: '0.9rem', whiteSpace: 'pre-wrap', background: 'var(--secondary)', padding: '0.5rem', borderRadius: 'var(--radius-sm)' },
    complianceTestControls: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', background: 'var(--card)', padding: '1rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)', flexWrap: 'wrap' },
    testResultsContainer: { marginTop: '1.5rem', },
    testResultsHeader: { marginBottom: '1rem', color: 'var(--foreground-heavy)' },
    testResultItem: { background: 'var(--card)', padding: '1rem', borderRadius: 'var(--radius)', border: '1px solid var(--border)', marginBottom: '1rem' },
    testResultQuestion: { margin: 0, fontWeight: '500' },
    testResultAnswer: { marginTop: '0.75rem', paddingTop: '0.75rem', borderTop: '1px solid var(--border)', color: 'var(--muted-foreground)' },
    promptContainer: {
        display: 'flex',
        gap: '1.5rem',
        flexWrap: 'wrap',
        alignItems: 'flex-start',
        marginBottom: '1.25rem',
    },
    promptColumn: {
        flex: 1,
        minWidth: '320px',
        display: 'flex',
        flexDirection: 'column',
    },
    personaItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)' },
    personaName: { margin: 0, fontWeight: 600 },
    personaPrompt: { margin: '0.25rem 0 0', color: 'var(--muted-foreground)', fontSize: '0.9rem' },
    personaActions: { display: 'flex', gap: '0.5rem' },
    apiKeyTypeChip: { background: 'var(--border)', color: 'var(--muted-foreground)', padding: '0.2rem 0.6rem', borderRadius: '12px', fontSize: '0.75rem', marginLeft: '0.5rem', display: 'inline-block', fontWeight: 500 },
    statusIndicator: { width: '10px', height: '10px', borderRadius: '50%', flexShrink: 0 },
    personaStages: { marginTop: '0.5rem', fontSize: '0.8rem', color: '#666', fontStyle: 'italic' },
    complianceContentPreview: { margin: '0.5rem 0 0', color: 'var(--muted-foreground)', fontSize: '0.85rem', whiteSpace: 'pre-wrap', background: 'var(--secondary)', padding: '0.5rem', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border)', maxHeight: '100px', overflow: 'hidden' },
    shareGroup: { marginBottom: '1.5rem', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' },
    shareGroupTitle: { margin: 0, padding: '1rem 1.25rem', background: 'var(--secondary)', borderBottom: '1px solid var(--border)', fontWeight: 600 },
    modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(16, 24, 40, 0.6)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 3000, padding: '1rem' },
    modalContent: {
        background: 'var(--card)',
        color: 'var(--foreground)',
        padding: '0',
        borderRadius: 'var(--radius-lg)',
        position: 'relative',
        width: '95%',
        maxWidth: '780px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: 'var(--shadow-lg)',
        overflow: 'hidden'
    },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', flexShrink: 0 },
    modalBody: { padding: '1.5rem', overflowY: 'auto', flexGrow: 1 },
    modalCloseButton: { background: 'transparent', border: 'none', color: 'var(--muted-foreground)', cursor: 'pointer', borderRadius: '50%', padding: '0.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    modalTitle: { margin: '0', fontSize: '1.125rem', fontWeight: 600, color: 'var(--foreground-heavy)' },
    modalFooter: { display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', padding: '1rem 1.5rem', borderTop: '1px solid var(--border)', background: 'var(--secondary)', flexShrink: 0 },
};

export default adminStyles;
